### ISSUE TITLE
Loading next question every 5 seconds

### ISSUE THREAD

**Issue by vsevjednom-cz** [gagan257/Mini-Project#5]
Hiii, your Mini-Project is amazing but I have a little problem and I can't do resolution: When I'm at the fifth or next question, your Javascript reloads next question every 5 seconds. Can I disable it?

**Comment by gagan257** [comment]
Thank you for your kind words about my Mini-Project. I'm sorry to hear that you're experiencing an issue with the script reloading the next question every 5 seconds. To disable this feature, you can simply comment out or delete the code that is responsible for the automatic reloading of the questions. Please let me know if you need any further assistance with this issue, and I'll be happy to help.

**Comment by vsevjednom-cz** [comment]
Thank you! But what part of code doing it?

**Comment by gagan257** [comment]
You can checkout "test-questions.html" file , from line 40. There you will find a carousel made using bootstrap

**Comment by vsevjednom-cz** [comment]
`<div class="carousel slide mt-3" id="myCarousel3">`
?
Thanks!
It works when I delete "carousel" class but also not works clicks to the next or prev. I need to click to the prev or next but I want to disable automatic next.

**Comment by gagan257** [comment]
Thanks for Pointing the error.
I just updated the code. Add a new attribute " data-interval="false" " It will fix auto sliding problem.
You can check the updated code now
Please let me know if you need any further assistance with this issue, and I'll be happy to help.

**Comment by vsevjednom-cz** [comment]
Wow, it's amazing! Thank you!
